export const customEn = {
    CODING_MOTION_S: 'Move %1 Steps Forward %2',
    CODING_MOTION_S_1: 'Move 1 Step Forward %1',
    CODING_MOTION_S_2: 'Move 2 Steps Forward %1',
    CODING_MOTION_S_3: 'Move 3 Steps Forward %1',
    CODING_MOTION_SWF: 'Swim %1 Steps Freestyle %2',
    CODING_MOTION_SWF_1: 'Swim 1 Step Freestyle %1',
    CODING_MOTION_SWF_2: 'Swim 2 Steps Freestyle %1',
    CODING_MOTION_SWF_3: 'Swim 3 Steps Freestyle %1',
    CODING_MOTION_SB: 'Move %1 Steps Backward %2',
    CODING_MOTION_SB_1: 'Move 1 Step Backward %1',
    CODING_MOTION_SB_2: 'Move 2 Steps Backward %1',
    CODING_MOTION_SB_3: 'Move 3 Steps Backward %1',
    CODING_MOTION_SWB: 'Swim %1 Steps Backstroke %2',
    CODING_MOTION_SWB_1: 'Swim 1 Step Backstroke %1',
    CODING_MOTION_SWB_2: 'Swim 2 Steps Backstroke %1',
    CODING_MOTION_SWB_3: 'Swim 3 Steps Backstroke %1',
    CODING_MOTION_TR: 'Turn Right %1',
    CODING_MOTION_TL: 'Turn Left %1',
    CODING_MOTION_TA: 'Turn Around %1',
    CODING_MOTION_J: 'Jump %1',
    CODING_MOTION_SD_1: 'Slide 1 Step Forward %1',
    CODING_MOTION_SD_2: 'Slide 2 Steps Forward %1',
    CODING_MOTION_SD_3: 'Slide 3 Steps Forward %1',
    CODING_MOTION_SD: 'Slide %1 Steps Forward %2',
    CODING_MOTION_ST: 'Yell %1',
    CODING_MOTION_CI: 'Break the Ice %1',
    CODING_MOTION_CS: 'Remove the Snow %1',
    CODING_MOTION_PU: 'Pick Up %1',
    CODING_MOTION_FF: 'Feed Forward %1',
    CODING_MOTION_FR: 'Feed Right %1',
    CODING_MOTION_FL: 'Feed Left %1',
    CODING_MOTION_FI: 'Fish %1',
    CODING_MOTION_D: 'Dive %1',
    CODING_MOTION_TN: 'Turn On %1',
    CODING_MOTION_TF: 'Turn Off %1',
    CODING_MOTION_MG: 'Make the Gate %1',
    CODING_MOTION_T: 'Trim the Ice %1',
    CODING_MOTION_FIX: 'Fix the Igloo %1',
    CODING_MOTION_DF: 'Drive %1 Steps Forward %2',
    CODING_MOTION_DF_1: 'Drive 1 Step Forward %1',
    CODING_MOTION_DF_2: 'Drive 2 Steps Forward %1',
    CODING_MOTION_DF_3: 'Drive 3 Steps Forward %1',
    CODING_MOTION_DB: 'Drive %1 Steps Backward %2',
    CODING_MOTION_DB_1: 'Drive 1 Step Backward %1',
    CODING_MOTION_DB_2: 'Drive 2 Steps Backward %1',
    CODING_MOTION_DB_3: 'Drive 3 Steps Backward %1',

    CODING_CONTROL_START: 'Begin %1',
    CODING_CONTROL_END: 'End %1',
    CODING_CONTROL_R: 'Repeat %1 times %2',
    CODING_CONTROL_R_2: 'Repeat 2 times %1',
    CODING_CONTROL_R_3: 'Repeat 3 times %1'
};
