export const customKo = {
    CODING_MOTION_S: '앞으로 %1 칸 이동하기 %2',
    CODING_MOTION_S_1: '앞으로 1 칸 이동하기 %1',
    CODING_MOTION_S_2: '앞으로 2 칸 이동하기 %1',
    CODING_MOTION_S_3: '앞으로 3 칸 이동하기 %1',
    CODING_MOTION_SWF: '앞으로 %1 칸 헤엄치기 %2',
    CODING_MOTION_SWF_1: '앞으로 1 칸 헤엄치기 %1',
    CODING_MOTION_SWF_2: '앞으로 2 칸 헤엄치기 %1',
    CODING_MOTION_SWF_3: '앞으로 3 칸 헤엄치기 %1',
    CODING_MOTION_SB: '뒤로 %1 칸 이동하기 %2',
    CODING_MOTION_SB_1: '뒤로 1 칸 이동하기 %1',
    CODING_MOTION_SB_2: '뒤로 2 칸 이동하기 %1',
    CODING_MOTION_SB_3: '뒤로 3 칸 이동하기 %1',
    CODING_MOTION_SWB: '뒤로 %1 칸 헤엄치기 %2',
    CODING_MOTION_SWB_1: '뒤로 1 칸 헤엄치기 %1',
    CODING_MOTION_SWB_2: '뒤로 2 칸 헤엄치기 %1',
    CODING_MOTION_SWB_3: '뒤로 3 칸 헤엄치기 %1',
    CODING_MOTION_TR: '오른쪽으로 돌기 %1',
    CODING_MOTION_TL: '왼쪽으로 돌기 %1',
    CODING_MOTION_TA: '제자리 돌기 %1',
    CODING_MOTION_J: '점프하기 %1',
    CODING_MOTION_SD_1: '앞으로 1 칸 슬라이딩하기 %1',
    CODING_MOTION_SD_2: '앞으로 2 칸 슬라이딩하기 %1',
    CODING_MOTION_SD_3: '앞으로 3 칸 슬라이딩하기 %1',
    CODING_MOTION_SD: '앞으로 %1 칸 슬라이딩하기 %2',
    CODING_MOTION_ST: '소리치기 %1',
    CODING_MOTION_CI: '얼음 깨기 %1',
    CODING_MOTION_CS: '눈 치우기 %1',
    CODING_MOTION_PU: '줍기 %1',
    CODING_MOTION_FF: '앞에 먹이 주기 %1',
    CODING_MOTION_FR: '오른쪽에 먹이 주기 %1',
    CODING_MOTION_FL: '왼쪽에 먹이 주기 %1',
    CODING_MOTION_FI: '물고기 잡기 %1',
    CODING_MOTION_D: '다이빙하기 %1',
    CODING_MOTION_TN: '시동 켜기 %1',
    CODING_MOTION_TF: '시동 끄기 %1',
    CODING_MOTION_MG: '대문 만들기 %1',
    CODING_MOTION_T: '얼음 다듬기 %1',
    CODING_MOTION_FIX: '이글루 고치기 %1',
    CODING_MOTION_DF: '앞으로 %1 칸 운전하기 %2',
    CODING_MOTION_DF_1: '앞으로 1 칸 운전하기 %1',
    CODING_MOTION_DF_2: '앞으로 2 칸 운전하기 %1',
    CODING_MOTION_DF_3: '앞으로 3 칸 운전하기 %1',
    CODING_MOTION_DB: '뒤로 %1 칸 운전하기 %2',
    CODING_MOTION_DB_1: '뒤로 1 칸 운전하기 %1',
    CODING_MOTION_DB_2: '뒤로 2 칸 운전하기 %1',
    CODING_MOTION_DB_3: '뒤로 3 칸 운전하기 %1',

    CODING_CONTROL_START: '시작하기 %1',
    CODING_CONTROL_END: '끝내기 %1',
    CODING_CONTROL_R: '%1 번 반복하기 %2',
    CODING_CONTROL_R_2: '2 번 반복하기 %1',
    CODING_CONTROL_R_3: '3 번 반복하기 %1'
};
